int _putchar(char c);
void print_alphabet(void);
void print_alphabet_x10(void);
int _isupper(int c);
int _isdigit(int c);
int mul(int a, int b);
void print_numbers(void);
void print_most_numbers(void);
int print_sign(int n);
void print_line(int n);
void print_diagonal(int n);
void more_numbers(void);
void times_table(void);
int add(int, int);
void print_to_98(int n);
void print_times_table(int n);
